module.exports = [
  {
    "Timestamp": "12/2/2021 22:58:01",
    "Email Address": "tapasts@rknec.edu",
    "Name": "Tejas Sudhir Tapas",
    "Year of Study": "4ᵗʰ",
    "Role": "GDSC lead",
    "Description (like the one highlighted in the following image)": "Open Source Developer | Hackathon Enthusiast | MLSA",
    "Linked in profile URL": "https://www.linkedin.com/in/tejas-sudhir-tapas-971847171/",
    "Email Id (preferably rknec)": "tapasts@rknec.edu",
    "GitHub profile URL": "https://github.com/Tejas1510",
    "Profile Picture": "https://drive.google.com/open?id=1DvHBee3QCgBg3BWODmbsAo__rWpK4K3B"
  },
  {
    "Timestamp": "12/3/2021 9:26:35",
    "Email Address": "valssonj@rknec.edu",
    "Name": "Jereen Valsson",
    "Year of Study": "4ᵗʰ",
    "Role": "Program Manager",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast , Data Structure",
    "Linked in profile URL": "https://www.linkedin.com/in/jereenvalsson",
    "Email Id (preferably rknec)": "valssonj@rknec.edu",
    "GitHub profile URL": "https://github.com/jereenv",
    "Profile Picture": "https://drive.google.com/open?id=18jsxriLW8yssKcmlkycHi-a6poLxtsiZ"
  },
  {
    "Timestamp": "12/4/2021 13:46:34",
    "Email Address": "mahallebc@rknec.edu",
    "Name": "Bhagyashree Mahalle",
    "Year of Study": "4ᵗʰ",
    "Role": "Graphics Designer",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast | Developer | Innovative Thinker",
    "Linked in profile URL": "www.linkedin.com/in/bhagyashreemahalle",
    "Email Id (preferably rknec)": "mahallebc@rknec.edu",
    "GitHub profile URL": "",
    "Profile Picture": "https://drive.google.com/open?id=1TaQQK7UiO0Z8GFYs5SVN0dX4rT7qN2i1"
  },
  {
    "Timestamp": "12/4/2021 14:02:20",
    "Email Address": "talmaless@rknec.edu",
    "Name": "Sanskruti Sanjay Talmale",
    "Year of Study": "4ᵗʰ",
    "Role": "Program Manager",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast | Developer | Innovative Thinker",
    "Linked in profile URL": "https://www.linkedin.com/in/sanskrutitalmale/",
    "Email Id (preferably rknec)": "talmaless@rknec.edu",
    "GitHub profile URL": "",
    "Profile Picture": "https://drive.google.com/open?id=1yVJ6-4pn1yt3k3jesIjF5aof0I5M46SS"
  },
  {
    "Timestamp": "12/4/2021 14:41:08",
    "Email Address": "agrawaltd@rknec.edu",
    "Name": "Tanisha Agrawal",
    "Year of Study": "4ᵗʰ",
    "Role": "Program Manager",
    "Description (like the one highlighted in the following image)": "Full Stack Developer|Data Scientitist| Weirdo",
    "Linked in profile URL": "https://www.linkedin.com/in/tanisha-agrawal-6b9a52196/",
    "Email Id (preferably rknec)": "agrawaltd@rknec.edu",
    "GitHub profile URL": "https://github.com/Tan-isha-agrawal",
    "Profile Picture": "https://drive.google.com/open?id=1EIWyXpmfpcgIk02-n8xw_7UkLIRQjnmz"
  },
  {
    "Timestamp": "12/10/2021 11:35:50",
    "Email Address": "rathirp@rknec.edu",
    "Name": "Rishabh Rathi",
    "Year of Study": "4ᵗʰ",
    "Role": "Management Head",
    "Description (like the one highlighted in the following image)": "Learner | Full Stack Dev",
    "Linked in profile URL": "https://www.linkedin.com/in/rishabhrathi22/",
    "Email Id (preferably rknec)": "rathirp@rknec.edu",
    "GitHub profile URL": "https://github.com/rishabhrathi22/",
    "Profile Picture": "https://drive.google.com/open?id=1BiiEa2pV_UD_T9ZxrsYJbGUbHnPEhz3U"
  },
  {
    "Timestamp": "12/10/2021 12:01:50",
    "Email Address": "saboosa@rknec.edu",
    "Name": "Shubham Saboo",
    "Year of Study": "4ᵗʰ",
    "Role": "Content Creator",
    "Description (like the one highlighted in the following image)": "Data Science Enthusiast | Machine Learning | Avid reader",
    "Linked in profile URL": "https://www.linkedin.com/in/shubham-saboo-2000",
    "Email Id (preferably rknec)": "saboosa@rknec.edu",
    "GitHub profile URL": "https://github.com/Shubham-Saboo",
    "Profile Picture": "https://drive.google.com/open?id=16cikSwPgz4VrePIvI9PWqp0GkjC46ugb"
  },
  {
    "Timestamp": "12/2/2021 23:42:14",
    "Email Address": "dhirangp@rknec.edu",
    "Name": "Gaurav Dhiran",
    "Year of Study": "3ʳᵈ",
    "Role": "Web Developer",
    "Description (like the one highlighted in the following image)": "Reader |Programmer | Developer",
    "Linked in profile URL": "https://www.linkedin.com/in/gaurav-dhiran-649b50206",
    "Email Id (preferably rknec)": "dhirangp@rknec.edu",
    "GitHub profile URL": "https://github.com/gaurav220701",
    "Profile Picture": "https://drive.google.com/open?id=1bHuxE7eczkuM8bmyW5MyH-xz-8QsjZCp"
  },
  {
    "Timestamp": "12/3/2021 14:22:01",
    "Email Address": "lakhwanihp_1@rknec.edu",
    "Name": "Hevesh Lakhwani",
    "Year of Study": "3ʳᵈ",
    "Role": "Flutter Developer",
    "Description (like the one highlighted in the following image)": "Flutter Enthusiast | Pythonist | Fast Learner",
    "Linked in profile URL": "https://www.linkedin.com/in/hevesh/",
    "Email Id (preferably rknec)": "lakhwanihp_1@rknec.edu",
    "GitHub profile URL": "https://github.com/HeveshL",
    "Profile Picture": "https://drive.google.com/open?id=1SpbeT8aKLk25JiOqjyvyn21jI1Mf570Q"
  },
  {
    "Timestamp": "12/3/2021 14:23:06",
    "Email Address": "joshirr_2@rknec.edu",
    "Name": "Rishikesh Joshi",
    "Year of Study": "3ʳᵈ",
    "Role": "Web Developer",
    "Description (like the one highlighted in the following image)": "Web Developer|Team Player|React Enthusiast|Problem Solving",
    "Linked in profile URL": "https://www.linkedin.com/in/rishikesh-joshi-9660931a5/",
    "Email Id (preferably rknec)": "joshirr_2@rknec.edu",
    "GitHub profile URL": "https://github.com/immortal-j",
    "Profile Picture": "https://drive.google.com/open?id=1nKg2v4DvRW1Y-EcxTK7r_kyLiQKtNyMP"
  },
  {
    "Timestamp": "12/3/2021 15:51:07",
    "Email Address": "jodhpurkaror@rknec.edu",
    "Name": "Om Jodhpurkar",
    "Year of Study": "3ʳᵈ",
    "Role": "Content Creator",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast | Musician",
    "Linked in profile URL": "https://www.linkedin.com/in/omjodhpurkar/",
    "Email Id (preferably rknec)": "ojodhpurkar@gmail.com",
    "GitHub profile URL": "https://github.com/infinity811",
    "Profile Picture": "https://drive.google.com/open?id=1szhpf4N2VHYPkb7KiH6cGiZMKCvfDuE_"
  },
  {
    "Timestamp": "12/4/2021 19:11:27",
    "Email Address": "lakhwanihp@rknec.edu",
    "Name": "Henay Lakhwani",
    "Year of Study": "3ʳᵈ",
    "Role": "Graphics Designer",
    "Description (like the one highlighted in the following image)": "Motion Graphics Designer | UI/UX Designer | Creative Mind",
    "Linked in profile URL": "https://www.linkedin.com/in/henay-lakhwani-502987192/",
    "Email Id (preferably rknec)": "lakhwanihp@rknec.edu",
    "GitHub profile URL": "https://github.com/henaylakhwani",
    "Profile Picture": "https://drive.google.com/open?id=1OKXf2_96NuWhK_F7ZCKQCyZp7IGTce--"
  },
  {
    "Timestamp": "12/4/2021 23:12:10",
    "Email Address": "chouhanvr_1@rknec.edu",
    "Name": "Vaishnavi Chouhan",
    "Year of Study": "3ʳᵈ",
    "Role": "Competitive problem setter",
    "Description (like the one highlighted in the following image)": "Learner | Problem solver",
    "Linked in profile URL": "https://www.linkedin.com/in/vaishnavi-chouhan-1a9661198",
    "Email Id (preferably rknec)": "chouhanvr_1@rknec.edu",
    "GitHub profile URL": "",
    "Profile Picture": "https://drive.google.com/open?id=1MwEhiNN6q3tA9tc-o-QhUXsgvS6fMquP"
  },
  {
    "Timestamp": "12/7/2021 13:20:31",
    "Email Address": "pandhaream1@rknec.edu",
    "Name": "Atharva Pandhare",
    "Year of Study": "3ʳᵈ",
    "Role": "Web Developer",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast | Developer",
    "Linked in profile URL": "https://www.linkedin.com/in/atharva-pandhare-3325a820a/",
    "Email Id (preferably rknec)": "pandhaream1@rknec.edu",
    "GitHub profile URL": "https://github.com/Atharva-17",
    "Profile Picture": "https://drive.google.com/open?id=1-sEBGhiNK9oWHRR2tGvkJu4AlpwdRFqX"
  },
  {
    "Timestamp": "12/10/2021 11:38:51",
    "Email Address": "niralara@rknec.edu",
    "Name": "Rituj Aryan",
    "Year of Study": "3ʳᵈ",
    "Role": "Competitive Problem Setter",
    "Description (like the one highlighted in the following image)": "Competitive Programmer | Backend Developer",
    "Linked in profile URL": "https://www.linkedin.com/in/ritujaryan/",
    "Email Id (preferably rknec)": "niralara@rknec.edu",
    "GitHub profile URL": "https://github.com/ritujaryan",
    "Profile Picture": "https://drive.google.com/open?id=1tJ4tjSW22HG3D9zi-S7Pr_o4iy1qNtr8"
  },
  {
    "Timestamp": "12/10/2021 11:51:39",
    "Email Address": "joshisd@rknec.edu",
    "Name": "Shubham joshi",
    "Year of Study": "3ʳᵈ",
    "Role": "Mobile application developer",
    "Description (like the one highlighted in the following image)": "Tech Enthusiastic | Flutter Developer",
    "Linked in profile URL": "https://www.linkedin.com/in/shubham-joshi-471195191",
    "Email Id (preferably rknec)": "joshisd@rknec.edu",
    "GitHub profile URL": "",
    "Profile Picture": "https://drive.google.com/open?id=1Kb0tttDxTTbDsnhC0LU-fFxo72iptXXg"
  },
  {
    "Timestamp": "12/2/2021 22:31:02",
    "Email Address": "parmarth_1@rknec.edu",
    "Name": "Twinshu Parmar",
    "Year of Study": "2ⁿᵈ",
    "Role": "Web Developer",
    "Description (like the one highlighted in the following image)": "Learner | Programmer | Diligent",
    "Linked in profile URL": "https://www.linkedin.com/in/twinshu-parmar-84b5bb209/",
    "Email Id (preferably rknec)": "parmarth_1@rknec.edu",
    "GitHub profile URL": "https://github.com/twi05",
    "Profile Picture": "https://drive.google.com/open?id=1jLGdNNYqfGpnvqfkl27wEv5u6ZoHiE7M"
  },
  {
    "Timestamp": "12/2/2021 22:36:48",
    "Email Address": "jaints@rknec.edu",
    "Name": "Tanmay Jain",
    "Year of Study": "2ⁿᵈ",
    "Role": "Program Manager",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast | Manager | Coder",
    "Linked in profile URL": "https://www.linkedin.com/in/tanmay-jain-136159206/",
    "Email Id (preferably rknec)": "jaints@rknec.edu",
    "GitHub profile URL": "https://github.com/tjain17",
    "Profile Picture": "https://drive.google.com/open?id=1Et-7nVZNV1TxO_dAoWdkpNId_PgdGysn"
  },
  {
    "Timestamp": "12/2/2021 22:45:12",
    "Email Address": "joshias_2@rknec.edu",
    "Name": "Akshada Joshi",
    "Year of Study": "2ⁿᵈ",
    "Role": "Program Manager",
    "Description (like the one highlighted in the following image)": "Explorer | Programming Freak",
    "Linked in profile URL": "https://www.linkedin.com/in/akshada-joshi-6143b21b3/",
    "Email Id (preferably rknec)": "joshias_2@rknec.edu",
    "GitHub profile URL": "https://github.com/joshiakshada0404",
    "Profile Picture": "https://drive.google.com/open?id=1haOTwdxBmcwc33rHFmh23JPHzX1jqEv8"
  },
  {
    "Timestamp": "12/2/2021 22:52:32",
    "Email Address": "tankkp@rknec.edu",
    "Name": "Ketaki tank",
    "Year of Study": "2ⁿᵈ",
    "Role": "Graphics Designer",
    "Description (like the one highlighted in the following image)": "Coding Enthusiast | Aesthete | Curious Soul",
    "Linked in profile URL": "https://www.linkedin.com/in/ketaki-tank/",
    "Email Id (preferably rknec)": "tankkp@rknec.edu",
    "GitHub profile URL": "https://github.com/ketakitankk",
    "Profile Picture": "https://drive.google.com/open?id=15IQ5IiuN5OQhnapFy5vGcX7-lyeXPZSB"
  },
  {
    "Timestamp": "12/2/2021 23:14:39",
    "Email Address": "jawadiss@rknec.edu",
    "Name": "Siddhesh Jawadi",
    "Year of Study": "2ⁿᵈ",
    "Role": "Program Manager",
    "Description (like the one highlighted in the following image)": "Technocrat, Code Junkie, Computer Nerd",
    "Linked in profile URL": "https://www.linkedin.com/in/siddhesh-jawadi-310631225",
    "Email Id (preferably rknec)": "jawadiss@rknec.edu",
    "GitHub profile URL": "https://github.com/SiddheshJawadi",
    "Profile Picture": "https://drive.google.com/open?id=1oKobOwA72WKq_8wxewzuygBGeJA8Dq89"
  },
  {
    "Timestamp": "12/3/2021 0:59:20",
    "Email Address": "sheteas@rknec.edu",
    "Name": "Ayush Shete",
    "Year of Study": "2ⁿᵈ",
    "Role": "Web Developer",
    "Description (like the one highlighted in the following image)": "Al enthusiast | Python programmer | Full Stack Web Developer",
    "Linked in profile URL": "https://www.linkedin.com/in/ayushshete",
    "Email Id (preferably rknec)": "sheteas@rknec.edu",
    "GitHub profile URL": "https://github.com/ayushete2005",
    "Profile Picture": "https://drive.google.com/open?id=1F4ikgyQ5oSwsU8sJ3Cj0v3V8sB5tM9i1"
  },
  {
    "Timestamp": "12/3/2021 14:07:51",
    "Email Address": "thakrers@rknec.edu",
    "Name": "Rutuja Thakre",
    "Year of Study": "2ⁿᵈ",
    "Role": "Graphics Designer",
    "Description (like the one highlighted in the following image)": "Designer|Developer|Conscientious learner",
    "Linked in profile URL": "https://www.linkedin.com/in/rutuja-thakre-a4284a206",
    "Email Id (preferably rknec)": "thakrers@rknec.edu",
    "GitHub profile URL": "https://github.com/Rutuja2109",
    "Profile Picture": "https://drive.google.com/open?id=1bmr95NxeyRRMdJlyc7RthpEh6D5Jijab"
  },
  {
    "Timestamp": "12/3/2021 15:06:03",
    "Email Address": "rayaladr@rknec.edu",
    "Name": "Darshan Rayala",
    "Year of Study": "2ⁿᵈ",
    "Role": "Video Editor",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast | Front-End Developer | Video Editor | Competitive Programmer",
    "Linked in profile URL": "www.linkedin.com/in/darshan-rayala",
    "Email Id (preferably rknec)": "rayaladr@rknec.edu",
    "GitHub profile URL": "https://github.com/DarshanRayala",
    "Profile Picture": "https://drive.google.com/open?id=1PU9NPAfRHrQ0pm7v9auDmuqRCGDP1mGu"
  },
  {
    "Timestamp": "12/3/2021 16:08:30",
    "Email Address": "agrawalpa_4@rknec.edu",
    "Name": "Pratik Agrawal",
    "Year of Study": "2ⁿᵈ",
    "Role": "Web Developer",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast | Web Developer | Leader",
    "Linked in profile URL": "https://www.linkedin.com/in/rudrapratik/",
    "Email Id (preferably rknec)": "agrawalpa_4@rknec.edu",
    "GitHub profile URL": "https://github.com/RudraPratik30",
    "Profile Picture": "https://drive.google.com/open?id=1WaZdPBJZXTFaPnUzZbnbUmjUs26ds7rp"
  },
  {
    "Timestamp": "12/3/2021 18:19:35",
    "Email Address": "khannaam@rknec.edu",
    "Name": "Aashi Khanna",
    "Year of Study": "2ⁿᵈ",
    "Role": "Content Creator",
    "Description (like the one highlighted in the following image)": "Creative Thinker | Tech Buff",
    "Linked in profile URL": "http://linkedin.com/in/aashi-khanna-a4abbb208",
    "Email Id (preferably rknec)": "khannaam@rknec.edu",
    "GitHub profile URL": "https://github.com/aashiikhannaa",
    "Profile Picture": "https://drive.google.com/open?id=1x_vcFhao6yNK7JEbj7JbgKazjOOFrMRs"
  },
  {
    "Timestamp": "12/4/2021 10:40:34",
    "Email Address": "jhamd@rknec.edu",
    "Name": "Madhav Jha",
    "Year of Study": "2ⁿᵈ",
    "Role": "Web Developer",
    "Description (like the one highlighted in the following image)": "Competitive Programer | Full stack developer",
    "Linked in profile URL": "https://www.linkedin.com/in/jhamadhav/",
    "Email Id (preferably rknec)": "jhamd@rknec.edu",
    "GitHub profile URL": "https://github.com/jhamadhav",
    "Profile Picture": "https://drive.google.com/open?id=1-FrmEIzF23KEiA6mcMhJ2qMK_KD-QVQb"
  },
  {
    "Timestamp": "12/4/2021 10:44:47",
    "Email Address": "mandavgadejd@rknec.edu",
    "Name": "Janak Mandavgade",
    "Year of Study": "2ⁿᵈ",
    "Role": "Video Editor",
    "Description (like the one highlighted in the following image)": "Techie,gamer,Developer",
    "Linked in profile URL": "https://www.linkedin.com/in/janak-mandavgade/",
    "Email Id (preferably rknec)": "mandavgadejd@rknec.edu",
    "GitHub profile URL": "https://github.com/janakmandavgade",
    "Profile Picture": "https://drive.google.com/open?id=10a1Gdz2mvynRcWgzoHfOV-IpRZDxynmi"
  },
  {
    "Timestamp": "12/4/2021 15:40:22",
    "Email Address": "malviyal@rknec.edu",
    "Name": "Lokesh Malviya",
    "Year of Study": "2ⁿᵈ",
    "Role": "Program Manager",
    "Description (like the one highlighted in the following image)": "Tech Enthusiast | Extrovert | Developer",
    "Linked in profile URL": "www.linkedin.com/in/lokesh-malviya-42139a215",
    "Email Id (preferably rknec)": "malviyal@rknec.edu",
    "GitHub profile URL": "https://github.com/Lokesh-malviya",
    "Profile Picture": "https://drive.google.com/open?id=1t6gdLMCZA7njfBTvYs-oDkZeFA_TAEfy"
  },
  {
    "Timestamp": "12/5/2021 22:56:12",
    "Email Address": "guptarb@rknec.edu",
    "Name": "RITIKA GUPTA",
    "Year of Study": "2ⁿᵈ",
    "Role": "Program Manager",
    "Description (like the one highlighted in the following image)": "STEM lover, Innovative thinker,",
    "Linked in profile URL": "https://www.linkedin.com/in/ritika-gupta-13096a226",
    "Email Id (preferably rknec)": "guptarb@rknec.edu",
    "GitHub profile URL": "",
    "Profile Picture": "https://drive.google.com/open?id=1t6Cm68gsYz-LQ6ipFBNTt_Hi5mHunBqP"
  },
  {
    "Timestamp": "2/12/2022 12:37:55",
    "Email Address": "mundadakk@rknec.edu",
    "Name": "Krishna Mundada",
    "Year of Study": "2ⁿᵈ",
    "Branch": "AI & ML",
    "Shift": "1ˢᵗ",
    "Semester": "3ʳᵈ",
    "Mobile Number": 9607370383,
    "Role": "Video Editor",
    "Description (like the one highlighted in the following image)": "Ceaseless | Developer | Learner | Techie | Designer",
    "Linked in profile URL": "https://www.linkedin.com/in/krishna-mundada-106b1b204/",
    "Email Id (preferably rknec)": "mundadakk@rknec.edu",
    "GitHub profile URL": "https://github.com/krishna050702",
    "Profile Picture": "https://drive.google.com/open?id=1sO7-oZ8Hxmb1BzVICImNVl7W-K5r4O2P"
  },
  {
    "Timestamp": "2/12/2022 21:48:18",
    "Email Address": "sonivh@rknec.edu",
    "Name": "Vinayak Soni",
    "Year of Study": "2ⁿᵈ",
    "Branch": "AI & ML",
    "Shift": "1ˢᵗ",
    "Semester": "3ʳᵈ",
    "Mobile Number": 7709876880,
    "Role": "Graphics Designer",
    "Description (like the one highlighted in the following image)": "Technophile | Ingenious | Observer",
    "Linked in profile URL": "https://www.linkedin.com/in/vinayak-soni-2910b7213/",
    "Email Id (preferably rknec)": "sonivh@rknec.edu",
    "GitHub profile URL": "https://github.com/vinayaksoni143",
    "Profile Picture": "https://drive.google.com/open?id=1NZUK1_Skc1_6HTPzP-4aXlEaUVwTh1sn"
  }
]